# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.forgit]
github = "wfxr/forgit"

[plugins.fzf]
inline = 'eval "$(fzf --zsh)"'

[plugins.local-plugins]
local = "~/.config/zsh/"
use   = ["plugins/*.zsh"]
apply = ["source"]

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
